[package]
name = "static_init-test-suite"
version = "0.0.0"
publish = false

[dependencies.static_init]
path = ".."

[[test]]
name = "macro"
path = "tests/macro.rs"

[dev-dependencies]
lazy_static = "1.4"

